language: node_js
node_js:
  - "4"
  - "6"
after_success:
  - npm install codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec